### ISSUE TITLE
Fatal error installing Chakra Error: Got 403

### ISSUE THREAD

**Issue by rwaldron** [devsnek/esvu#10]
```
$ esvu
esvu ❯ version 1.2.0
Chakra ❯ Checking version...
Chakra ❯ Installing version 1_11_18
Chakra ❯ Downloading https://aka.ms/chakracore/cc_osx_x64_1_11_18
esvu ✖ Fatal error installing Chakra Error: Got 403
```

This has been preventing install of ChakraCore since at least April 16, because the last successful run of Test262.report's results collection engine was April 15.

**Comment by devsnek** [comment]
it looks like a problem with their server. I'm not really sure who to reach out to about that.

**Comment by rwaldron** [comment]
I'll see what I can learn

**Comment by rwaldron** [comment]
I've filed this: https://github.com/microsoft/ChakraCore/issues/6428
