### ISSUE TITLE
JSC path is slightly changed

### ISSUE THREAD

**Issue by Constellation** [devsnek/esvu#12]
It seems that name of JSC SHA256 files is changed from

`revision.sha256sum` to `revision.zip.sha256sum`.
https://webkitgtk.org/jsc-built-products/x86_64/release/?C=M;O=D
We should change esvu to handle both cases.

**Comment by devsnek** [comment]
Fixed in https://github.com/devsnek/esvu/commit/e40f90cef15a4924d1f9094fbe14c882b379b52a

**Comment by Constellation** [comment]
@devsnek Awesome! Thanks so much!!
