### ISSUE TITLE
Graaljs version isn't "latest"?

### ISSUE THREAD

**Issue by rwaldron** [devsnek/esvu#20]
If by default, esvu should be looking for the "latest" version when installing (unless explicitly specified?), then `resolveVersion` implementation for Graaljs is incorrect. Presently, it's getting 19.x, when the actual "latest" is 21.x (as of right now, that's 21.1.0), which is not a prerelease version.

**Comment by devsnek** [comment]
maybe a bug in github's release api? idk. the 19.x release has the highest id and its first in the list.

**Comment by rwaldron** [comment]
The published_at dates make more sense: 

19.3.6: 2021-04-20T13:38:57Z 
21.1.0: 2020-05-19T18:09:27Z

But even that wouldn't truly disambiguate, if they are still regularly releasing 19.x and 20.x

**Comment by rwaldron** [comment]
Alternatively, if esvu allowed me to do something like `esvu install engine@version --default`, so I could install whatever version I want without it being created as `engine-version`
