### ISSUE TITLE
xdg conventions on local esvu directory

### ISSUE THREAD

**Issue by mcarifio** [devsnek/esvu#22]
Ty for esvu. It's useful.

When I can, I like to follow the xdg conventions of my home directory. In the case of esvu, I'd like to put the installed engines in ~/.local/esvu rather than ~/.esvu. Or I might want to put esvu in `/opt/esvu` for other users to share. So I suggest the following:

1) if the global environment variable ESVU_PATH has a definition, respect that as the root

2) otherwise use ~/.esvu

I think the code in common.js would be:

```node
const ESVU_PATH = process.env.ESVU_PATH || path.join(os.homedir(), '.esvu'); // bin is added later
```

For the linux people, you might want to note that `~{user}` isn't expanded.

**Comment by ljharb** [comment]
rather than making a unique ESVU path, is there a reason not to read the appropriate XDG variable?

**Comment by devsnek** [comment]
I think both supporting `ESVU_PATH` and xdg would be good. What's the appropriate XDG var here? `XDG_CACHE_HOME`? `XFG_DATA_HOME`?

**Comment by mcarifio** [comment]
`XDG_DATA_HOME` according to https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html. Therefore:

```node
const ESVU_PATH = process.env.ESVU_PATH || process.env.XDG_DATA_HOME || path.join(os.homedir(), '.esvu'); // bin is added later
```

https://github.com/OpenPeeDeeP/xdg is an interesting take on being "xdg on different platforms". The danger here is reading the user's mind. And you already have some users with $HOME/.esvu.

**Comment by devsnek** [comment]
@ljharb @mcarifio how does this look? https://github.com/devsnek/esvu/commit/913d4dafa64abe5e854b040dca518b6b36143d2d
