### ISSUE TITLE
Requirements for engine inclusion?

### ISSUE THREAD

**Issue by alimpfard** [devsnek/esvu#32]
In particular, is having a binary release required, or is it okay to build from source as part of the install process?
Considering the engine I wish to add ([LibJS, the js engine in SerenityOS](https://github.com/SerenityOS/serenity/tree/master/Userland/Libraries/LibJS)) does not provide binary releases (as the development pace is far too fast to provide releases in general), is it at all possible to include LibJS in esvu?

**Comment by devsnek** [comment]
I don't think local builds would be a good fit for esvu. Maybe you could put ci artifacts somewhere? I think github has a thing for attaching them to the action runs, that might be doable if there's a way in the api to get the "latest" one.

**Comment by alimpfard** [comment]
Ah, fair enough.
Serenity is kind of a massive project, I don't think it'd make sense to start producing build artifacts with how frequent CI runs on the master branch are.

Thanks for answering, I'll close this issue for now.

**Comment by ljharb** [comment]
GitHub actions is free, and any tag automatically generates a zip file, so it doesn’t seem like it should matter if they do one a year or a thousand a day

**Comment by alimpfard** [comment]
I was mainly concerned with the size of the libraries we'd have to release along with the js engine, but after actually checking it, I've come to see that it's not _that_ bad, and stripping the binaries does make the size manageable.

I might make a PR about this later depending on how the whole release thing goes :)
