### ISSUE TITLE
Difference to GoogleChromeLabs/jsvu?

### ISSUE THREAD

**Issue by mikelnrd** [devsnek/esvu#8]
Hi. 
I just came across `esvu`. Can you share why you built it and the difference between `esvu` and `jsvu`? I notice it supports a couple of different engines. Any other reasons to use one over the other? 

Thanks in advance! 

PS: perhaps this could be added to the README?

**Comment by devsnek** [comment]
jsvu only supports engines that are self contained binaries. esvu will support any engine as long as there's a consistent place to download it from.

**Comment by mikelnrd** [comment]
Fantastic. Thanks a lot.
